version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bootdev-postgres
    environment:
      POSTGRES_USER: bootdev
      POSTGRES_PASSWORD: bootdev
      POSTGRES_DB: bootdevdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - bootdev-net

  mysql:
    image: mysql:8
    container_name: bootdev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: bootdev
      MYSQL_DATABASE: bootdevdb
      MYSQL_USER: bootdev
      MYSQL_PASSWORD: bootdev
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - bootdev-net
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer:latest
    container_name: bootdev-adminer
    ports:
      - "8080:8080"
    networks:
      - bootdev-net
    restart: unless-stopped
    depends_on:
      - postgres
      - mysql

networks:
  bootdev-net:
    driver: bridge

volumes:
  postgres_data:
  mysql_data:
